<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>R-project-patent</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="R-project-patent_files/libs/clipboard/clipboard.min.js"></script>
<script src="R-project-patent_files/libs/quarto-html/quarto.js"></script>
<script src="R-project-patent_files/libs/quarto-html/popper.min.js"></script>
<script src="R-project-patent_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="R-project-patent_files/libs/quarto-html/anchor.min.js"></script>
<link href="R-project-patent_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="R-project-patent_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="R-project-patent_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="R-project-patent_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="R-project-patent_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="R-project-patent.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">R-project-patent</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>GitHub Repository <a href="https://github.com/brl-noe/R-project-patent.git" class="uri">https://github.com/brl-noe/R-project-patent.git</a></p>
<section id="i--research-question-presentation" class="level1">
<h1>I- Research question presentation</h1>
<p>In early September, Mario Draghi revealed his plan to make the European Union more competitive. A key part of his plan is to invest billions in innovation. Patent applications serve as a proxy for innovation. A patent is an exclusive right granted for an invention, while a patent application refers to the legal and administrative process of requesting the issuance of a patent. This includes the content of the invention’s description and claims, along with the procedural paperwork involved. Therefore, it seems relevant to explore what factors influence the phenomenon of patent applications across European Union countries. Our research question is: <strong>What factors influence patent applications across European Union countries? A longitudinal analysis of education, innovation dynamics, and socioeconomic indicators.</strong></p>
<p>This study focuses on the role of education, innovation-related factors, and socioeconomic variables in explaining differences in patent activity across EU countries. We aim to determine whether higher educational attainment correlates with more patents and how economic factors, such as GDP, income inequality, and unemployment, influence this relationship.</p>
<p>Moreover, our study will employ a longitudinal analysis, allowing us to examine trends in patent applications and the evolution of the relationship between patent activity, education, and socioeconomic factors across European Union countries over time.We hypothesize that higher economic development is positively correlated with higher educational attainment and, in turn, with increased patent applications. In 2023, countries with the highest number of patent applications were also among the largest global economies (e.g., China ranked 1st, and the USA ranked 2nd), suggesting a link between economic strength and innovation output. This pattern implies that economic resources may facilitate investments in education and research, which are crucial drivers of technological advancement. Moreover, a World Bank article published in 2023 stated: <em>“Today, there is agreement that education, independent of innate ability, helps spur innovation and technology, and it contributes to productivity and economic growth.”</em> This further supports the idea that education plays a critical role in fostering innovation, reinforcing the need to investigate whether a similar relationship exists within European Union countries.</p>
<p>Our findings could help European policymakers allocate resources more effectively, ensuring that the billions of euros invested in innovation contribute to the European Union’s goal of remaining globally competitive. For instance, if we find that higher educational attainment correlates with higher patent applications, we would recommend that policymakers prioritize investments in education. This would potentially be more impactful and cost-effective than investing in other areas of the R&amp;D process, such as infrastructure.</p>
<p>&lt;&lt;&lt;&lt;&lt;&lt;&lt; HEAD Useful table of abbreviations for countries :</p>
<p>======= &gt;&gt;&gt;&gt;&gt;&gt;&gt; c307024afbb32af990d29c3c8479ee25a1d9e05e # II- Data sets descriptions</p>
<p>For our analysis, we will use tree different datasets all coming from the Eurostat public database: Population by Educational Attainment Level, Sex, and Age: <a href="https://ec.europa.eu/eurostat/web/products-datasets/-/edat_lfse_03" class="uri">https://ec.europa.eu/eurostat/web/products-datasets/-/edat_lfse_03</a> Patent Applications to the European Patent Office by Applicants’ / Inventors’ Country of Residence: <a href="https://ec.europa.eu/eurostat/web/products-datasets/-/sdg_09_40" class="uri">https://ec.europa.eu/eurostat/web/products-datasets/-/sdg_09_40</a> Key Indicators - Annual Data: <a href="https://ec.europa.eu/eurostat/web/products-datasets/-/nasa_10_ki" class="uri">https://ec.europa.eu/eurostat/web/products-datasets/-/nasa_10_ki</a></p>
<p>The common key indicator of the 3 datasets is <code>geo</code> that refers to the name of the country. This variable will be useful to associate datasets with each other. Another common variable to the 3 datasets is <code>unit</code> (percentage or a row value of the observed variable).</p>
<p>Then, the first dataset called patent has as observed value the number of requests for patent protection of an invention filed with the European Patent Office (EPO) regardless of whether they are granted or not. Here, we see a limit in our analysis coming from the last fact. Indeed, later on the analysis, we will proxy the level of innovation in a country based on this observed value of application for patent however we don’t actually know if the patent is granted or not, we mainly know which country (<code>geo</code>) applied for how many a patent each year.</p>
<p>The second dataset called education contains mainly contains the variable <code>isced11</code>. <code>isced11</code> is an indication of the the educational attainment level of an individual with each individual being in between 15 and 64 years old (variable <code>age</code>). The educational attainment level corresponds to the highest ISCED (International Standard Classification of Education) level successfully completed, the successful completion of an education programme being validated by a recognised qualification, in other word a qualification officially recognised by the relevant national education authorities or recognised as equivalent to another qualification of formal education. The ISCED for 2011 are as following:</p>
<p>Level 0 – Less than primary education Level 1 – Primary education Level 2 – Lower secondary education Level 3 – Upper secondary education Level 4 – Post-secondary non-tertiary education Level 5 – Short-cycle tertiary education Level 6 – Bachelor’s or equivalent level Level 7 – Master’s or equivalent level Level 8 – Doctoral or equivalent level</p>
<p>The third dataset called key_indicator encompass non-financial accounts that provide a description of the different stages of the economic process (variable <code>na_item</code>): production, generation of income, distribution of income, redistribution of income, use of income and non-financial accumulation. These stages are estimated in percentage for different sectors and agents of the economy of the country.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="R-project-patent_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>image_data <span class="ot">&lt;-</span> <span class="fu">readPNG</span>(<span class="st">"Table2.png"</span>)          </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, <span class="at">type =</span> <span class="st">"n"</span>, <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">main =</span> <span class="st">"Table2.png"</span>)  </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">rasterImage</span>(image_data, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">2</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="R-project-patent_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="basics-informations-about-the-databases" class="level2">
<h2 class="anchored" data-anchor-id="basics-informations-about-the-databases">Basics informations about the databases</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Loading the library</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(conflicted)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vroom)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ forcats   1.0.0     ✔ readr     2.1.5
✔ lubridate 1.9.4     ✔ tibble    3.2.1
✔ purrr     1.0.2     </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plm)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(AER)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Le chargement a nécessité le package : car
Le chargement a nécessité le package : carData

Attachement du package : 'car'

L'objet suivant est masqué depuis 'package:purrr':

    some

L'objet suivant est masqué depuis 'package:dplyr':

    recode

Le chargement a nécessité le package : lmtest
Le chargement a nécessité le package : zoo

Attachement du package : 'zoo'

Les objets suivants sont masqués depuis 'package:base':

    as.Date, as.Date.numeric

Le chargement a nécessité le package : sandwich
Le chargement a nécessité le package : survival</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sandwich)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_bw</span>())</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>conflicted<span class="sc">::</span><span class="fu">conflict_prefer</span>(<span class="st">"filter"</span>, <span class="st">"dplyr"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>[conflicted] Will prefer dplyr::filter over any other package.</code></pre>
</div>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Patent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Number of rows</td>
<td>152</td>
</tr>
<tr class="even">
<td>Number of columns</td>
<td>21</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Key Indicator</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Number of rows</td>
<td>682</td>
</tr>
<tr class="even">
<td>Number of columns</td>
<td>76</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Education</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Number of rows</td>
<td>6714</td>
</tr>
<tr class="even">
<td>Number of columns</td>
<td>33</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="iii--data-analysis" class="level1">
<h1>III- Data analysis</h1>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Data cleaning steps</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Separate columns</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>education <span class="ot">&lt;-</span> education <span class="sc">%&gt;%</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate</span>(<span class="at">col =</span> <span class="st">"freq,sex,age,unit,isced11,geo</span><span class="sc">\\</span><span class="st">TIME_PERIOD"</span>, </span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">into =</span> <span class="fu">c</span>(<span class="st">"freq"</span>, <span class="st">"sex"</span>, <span class="st">"age"</span>, <span class="st">"unit"</span>, <span class="st">"isced11"</span>, <span class="st">"geo"</span>),</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>           <span class="at">sep =</span> <span class="st">","</span>)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>patent <span class="ot">&lt;-</span> patent <span class="sc">%&gt;%</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate</span>(<span class="at">col =</span> <span class="st">"freq,coop_ptn,unit,geo</span><span class="sc">\\</span><span class="st">TIME_PERIOD"</span>, </span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>           <span class="at">into =</span> <span class="fu">c</span>(<span class="st">"freq"</span>, <span class="st">"coop_ptn"</span>, <span class="st">"unit"</span>, <span class="st">"geo"</span>),</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>           <span class="at">sep =</span> <span class="st">","</span>)</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>key_indicator <span class="ot">&lt;-</span> key_indicator <span class="sc">%&gt;%</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate</span>(<span class="at">col =</span> <span class="st">"freq,unit,na_item,sector,geo</span><span class="sc">\\</span><span class="st">TIME_PERIOD"</span>, </span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>           <span class="at">into =</span> <span class="fu">c</span>(<span class="st">"freq"</span>, <span class="st">"unit"</span>, <span class="st">"na_item"</span>, <span class="st">"sector"</span>, <span class="st">"geo"</span>),</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>           <span class="at">sep =</span> <span class="st">","</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="description-of-the-data-joining-cleaning-etc.-for-patent" class="level3">
<h3 class="anchored" data-anchor-id="description-of-the-data-joining-cleaning-etc.-for-patent">Description of the data joining, cleaning, etc. for patent</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 20
  `2004`   `2005` `2006` `2007` `2008` `2009` `2010` `2011` `2012` `2013` `2014`
  &lt;chr&gt;    &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt; 
1 charact… chara… chara… chara… chara… chara… chara… chara… chara… numer… chara…
# ℹ 9 more variables: `2015` &lt;chr&gt;, `2016` &lt;chr&gt;, `2017` &lt;chr&gt;, `2018` &lt;chr&gt;,
#   `2019` &lt;chr&gt;, `2020` &lt;chr&gt;, `2021` &lt;chr&gt;, `2022` &lt;chr&gt;, `2023` &lt;chr&gt;</code></pre>
</div>
</div>
<p>Here we find a problem in the patent dataset. Indeed, some Years have values in numeric format whereas some others are in the characters format</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: There were 18 warnings in `mutate()`.
The first warning was:
ℹ In argument: `across(starts_with("20"), ~as.numeric(as.character(.)))`.
Caused by warning:
! NAs introduits lors de la conversion automatique
ℹ Run `dplyr::last_dplyr_warnings()` to see the 17 remaining warnings.</code></pre>
</div>
</div>
<p>Mutate() will let us modify existing columns starting with “20” and the function across() will spread to all the functions staring with “20” the change from numeric values to characters.</p>
<p>We first create a column with all the years in it and each country’s values for every year:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3,040 × 6
   freq  coop_ptn unit  geo   Years Value
   &lt;chr&gt; &lt;chr&gt;    &lt;chr&gt; &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt;
 1 A     APPL     NR    AL    2004     NA
 2 A     APPL     NR    AL    2005     NA
 3 A     APPL     NR    AL    2006     NA
 4 A     APPL     NR    AL    2007     NA
 5 A     APPL     NR    AL    2008     NA
 6 A     APPL     NR    AL    2009      1
 7 A     APPL     NR    AL    2010      0
 8 A     APPL     NR    AL    2011      0
 9 A     APPL     NR    AL    2012      0
10 A     APPL     NR    AL    2013      0
# ℹ 3,030 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2,117 × 7
# Groups:   Years [19]
   freq  coop_ptn unit  geo   Years Value total_value
   &lt;chr&gt; &lt;chr&gt;    &lt;chr&gt; &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt;       &lt;dbl&gt;
 1 A     APPL     NR    AL    2009      1      74700.
 2 A     APPL     NR    AL    2010      0      81737.
 3 A     APPL     NR    AL    2011      0     145471.
 4 A     APPL     NR    AL    2012      0     147453.
 5 A     APPL     NR    AL    2013      0     151519.
 6 A     APPL     NR    AL    2014      3     155720.
 7 A     APPL     NR    AL    2015      0     159520.
 8 A     APPL     NR    AL    2016      2     159611.
 9 A     APPL     NR    AL    2017      0     163424.
10 A     APPL     NR    AL    2018      0     171375.
# ℹ 2,107 more rows</code></pre>
</div>
</div>
<p>Here we add an additional filter to remove the mean of patent in every country in the euro zone (EU27_2020). We need to do that because otherwise some countries in Europe will be counted two times (counted for themselves and inside the aggregate EU27_2020).</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="R-project-patent_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We see a global trend of increasing the total number of patent each year in the european countries.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 40 × 7
# Groups:   Years [19]
   freq  coop_ptn unit  geo       Years Value total_value
   &lt;chr&gt; &lt;chr&gt;    &lt;chr&gt; &lt;chr&gt;     &lt;chr&gt; &lt;dbl&gt;       &lt;dbl&gt;
 1 A     APPL     NR    EU27_2020 2004  51508      51627.
 2 A     APPL     NR    EU27_2020 2005  53744      53868.
 3 A     APPL     NR    EU27_2020 2006  55197      55323.
 4 A     APPL     NR    EU27_2020 2007  57255      57386.
 5 A     APPL     NR    EU27_2020 2008  60401      60401 
 6 A     APPL     NR    EU27_2020 2009  57101      57231.
 7 A     APPL     NR    EU27_2020 2010  61235      61235 
 8 A     APPL     NR    EU27_2020 2011  59626     119359 
 9 A     APPL     NR    EU27_2020 2012  60451     120790 
10 A     APPL     NR    EU27_2020 2013  61033     121993.
# ℹ 30 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="R-project-patent_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Similarly as before, if we only consider the 27 countries of the euro zone, we notice the same trend in the global number of patent.</p>
</section>
<section id="description-of-the-data-joining-cleaning-etc.-for-key-indicator" class="level3">
<h3 class="anchored" data-anchor-id="description-of-the-data-joining-cleaning-etc.-for-key-indicator">Description of the data joining, cleaning, etc. for key indicator</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 75
  `1949`   `1950` `1951` `1952` `1953` `1954` `1955` `1956` `1957` `1958` `1959`
  &lt;chr&gt;    &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt; 
1 charact… chara… chara… chara… chara… chara… chara… chara… chara… chara… chara…
# ℹ 64 more variables: `1960` &lt;chr&gt;, `1961` &lt;chr&gt;, `1962` &lt;chr&gt;, `1963` &lt;chr&gt;,
#   `1964` &lt;chr&gt;, `1965` &lt;chr&gt;, `1966` &lt;chr&gt;, `1967` &lt;chr&gt;, `1968` &lt;chr&gt;,
#   `1969` &lt;chr&gt;, `1970` &lt;chr&gt;, `1971` &lt;chr&gt;, `1972` &lt;chr&gt;, `1973` &lt;chr&gt;,
#   `1974` &lt;chr&gt;, `1975` &lt;chr&gt;, `1976` &lt;chr&gt;, `1977` &lt;chr&gt;, `1978` &lt;chr&gt;,
#   `1979` &lt;chr&gt;, `1980` &lt;chr&gt;, `1981` &lt;chr&gt;, `1982` &lt;chr&gt;, `1983` &lt;chr&gt;,
#   `1984` &lt;chr&gt;, `1985` &lt;chr&gt;, `1986` &lt;chr&gt;, `1987` &lt;chr&gt;, `1988` &lt;chr&gt;,
#   `1989` &lt;chr&gt;, `1990` &lt;chr&gt;, `1991` &lt;chr&gt;, `1992` &lt;chr&gt;, `1993` &lt;chr&gt;, …</code></pre>
</div>
</div>
<p>We observe again that many of the columns contains characters that we have to convert to numeric values.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>key_indicator2 <span class="ot">&lt;-</span> key_indicator <span class="sc">|&gt;</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">matches</span>(<span class="st">"^20|^19"</span>), <span class="sc">~</span> <span class="fu">as.numeric</span>(.)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: There were 75 warnings in `mutate()`.
The first warning was:
ℹ In argument: `across(matches("^20|^19"), ~as.numeric(.))`.
Caused by warning:
! NAs introduits lors de la conversion automatique
ℹ Run `dplyr::last_dplyr_warnings()` to see the 74 remaining warnings.</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(key_indicator2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 682 × 80
   freq  unit  na_item    sector geo   `1949` `1950` `1951` `1952` `1953` `1954`
   &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;      &lt;chr&gt;  &lt;chr&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
 1 A     PC    B2G_B3G_R… S11    AL        NA     NA     NA     NA     NA     NA
 2 A     PC    B2G_B3G_R… S11    AT        NA     NA     NA     NA     NA     NA
 3 A     PC    B2G_B3G_R… S11    BE        NA     NA     NA     NA     NA     NA
 4 A     PC    B2G_B3G_R… S11    BG        NA     NA     NA     NA     NA     NA
 5 A     PC    B2G_B3G_R… S11    CH        NA     NA     NA     NA     NA     NA
 6 A     PC    B2G_B3G_R… S11    CY        NA     NA     NA     NA     NA     NA
 7 A     PC    B2G_B3G_R… S11    CZ        NA     NA     NA     NA     NA     NA
 8 A     PC    B2G_B3G_R… S11    DE        NA     NA     NA     NA     NA     NA
 9 A     PC    B2G_B3G_R… S11    DK        NA     NA     NA     NA     NA     NA
10 A     PC    B2G_B3G_R… S11    EA20      NA     NA     NA     NA     NA     NA
# ℹ 672 more rows
# ℹ 69 more variables: `1955` &lt;dbl&gt;, `1956` &lt;dbl&gt;, `1957` &lt;dbl&gt;, `1958` &lt;dbl&gt;,
#   `1959` &lt;dbl&gt;, `1960` &lt;dbl&gt;, `1961` &lt;dbl&gt;, `1962` &lt;dbl&gt;, `1963` &lt;dbl&gt;,
#   `1964` &lt;dbl&gt;, `1965` &lt;dbl&gt;, `1966` &lt;dbl&gt;, `1967` &lt;dbl&gt;, `1968` &lt;dbl&gt;,
#   `1969` &lt;dbl&gt;, `1970` &lt;dbl&gt;, `1971` &lt;dbl&gt;, `1972` &lt;dbl&gt;, `1973` &lt;dbl&gt;,
#   `1974` &lt;dbl&gt;, `1975` &lt;dbl&gt;, `1976` &lt;dbl&gt;, `1977` &lt;dbl&gt;, `1978` &lt;dbl&gt;,
#   `1979` &lt;dbl&gt;, `1980` &lt;dbl&gt;, `1981` &lt;dbl&gt;, `1982` &lt;dbl&gt;, `1983` &lt;dbl&gt;, …</code></pre>
</div>
</div>
<p>Here we have a big problem because each sector has its own na_item that correspond to the method of calculation. In other words, in each countries the method to evaluate the percentage of each sector in the economy of the country is different. This fact limits the rigor of the approach for any analysis based on sectors.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 16,368 × 58
   freq  unit  na_item    sector geo   `1949` `1950` `1951` `1952` `1953` `1954`
   &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;      &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt; 
 1 A     PC    B2G_B3G_R… S11    AL    :      :      :      :      :      :     
 2 A     PC    B2G_B3G_R… S11    AL    :      :      :      :      :      :     
 3 A     PC    B2G_B3G_R… S11    AL    :      :      :      :      :      :     
 4 A     PC    B2G_B3G_R… S11    AL    :      :      :      :      :      :     
 5 A     PC    B2G_B3G_R… S11    AL    :      :      :      :      :      :     
 6 A     PC    B2G_B3G_R… S11    AL    :      :      :      :      :      :     
 7 A     PC    B2G_B3G_R… S11    AL    :      :      :      :      :      :     
 8 A     PC    B2G_B3G_R… S11    AL    :      :      :      :      :      :     
 9 A     PC    B2G_B3G_R… S11    AL    :      :      :      :      :      :     
10 A     PC    B2G_B3G_R… S11    AL    :      :      :      :      :      :     
# ℹ 16,358 more rows
# ℹ 47 more variables: `1955` &lt;chr&gt;, `1956` &lt;chr&gt;, `1957` &lt;chr&gt;, `1958` &lt;chr&gt;,
#   `1959` &lt;chr&gt;, `1960` &lt;chr&gt;, `1961` &lt;chr&gt;, `1962` &lt;chr&gt;, `1963` &lt;chr&gt;,
#   `1964` &lt;chr&gt;, `1965` &lt;chr&gt;, `1966` &lt;chr&gt;, `1967` &lt;chr&gt;, `1968` &lt;chr&gt;,
#   `1969` &lt;chr&gt;, `1970` &lt;chr&gt;, `1971` &lt;chr&gt;, `1972` &lt;chr&gt;, `1973` &lt;chr&gt;,
#   `1974` &lt;chr&gt;, `1975` &lt;chr&gt;, `1976` &lt;chr&gt;, `1977` &lt;chr&gt;, `1978` &lt;chr&gt;,
#   `1979` &lt;chr&gt;, `1980` &lt;chr&gt;, `1981` &lt;chr&gt;, `1982` &lt;chr&gt;, `1983` &lt;chr&gt;, …</code></pre>
</div>
</div>
</section>
<section id="description-of-the-data-joining-cleaningect.-for-education" class="level3">
<h3 class="anchored" data-anchor-id="description-of-the-data-joining-cleaningect.-for-education">Description of the data joining, cleaning,ect. for education</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 32
  `1992`   `1993` `1994` `1995` `1996` `1997` `1998` `1999` `2000` `2001` `2002`
  &lt;chr&gt;    &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt; 
1 charact… chara… chara… chara… chara… chara… chara… chara… chara… chara… chara…
# ℹ 21 more variables: `2003` &lt;chr&gt;, `2004` &lt;chr&gt;, `2005` &lt;chr&gt;, `2006` &lt;chr&gt;,
#   `2007` &lt;chr&gt;, `2008` &lt;chr&gt;, `2009` &lt;chr&gt;, `2010` &lt;chr&gt;, `2011` &lt;chr&gt;,
#   `2012` &lt;chr&gt;, `2013` &lt;chr&gt;, `2014` &lt;chr&gt;, `2015` &lt;chr&gt;, `2016` &lt;chr&gt;,
#   `2017` &lt;chr&gt;, `2018` &lt;chr&gt;, `2019` &lt;chr&gt;, `2020` &lt;chr&gt;, `2021` &lt;chr&gt;,
#   `2022` &lt;chr&gt;, `2023` &lt;chr&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: There were 32 warnings in `mutate()`.
The first warning was:
ℹ In argument: `across(matches("^20|^19"), ~as.numeric(.))`.
Caused by warning:
! NAs introduits lors de la conversion automatique
ℹ Run `dplyr::last_dplyr_warnings()` to see the 31 remaining warnings.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6,714 × 38
   freq  sex   age    unit  isced11 geo   `1992` `1993` `1994` `1995` `1996`
   &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;   &lt;chr&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
 1 A     F     Y15-64 PC    ED0-2   AT      NA     NA     NA     41.4   39.6
 2 A     F     Y15-64 PC    ED0-2   BA      NA     NA     NA     NA     NA  
 3 A     F     Y15-64 PC    ED0-2   BE      50.9   50.5   48.8   47.7   45.2
 4 A     F     Y15-64 PC    ED0-2   BG      NA     NA     NA     NA     NA  
 5 A     F     Y15-64 PC    ED0-2   CH      NA     NA     NA     NA     26.6
 6 A     F     Y15-64 PC    ED0-2   CY      NA     NA     NA     NA     NA  
 7 A     F     Y15-64 PC    ED0-2   CZ      NA     NA     NA     NA     NA  
 8 A     F     Y15-64 PC    ED0-2   DE      29.6   30.1   26.4   28.2   NA  
 9 A     F     Y15-64 PC    ED0-2   DK      36.6   27.8   30.7   28.6   NA  
10 A     F     Y15-64 PC    ED0-2   EA20    NA     NA     NA     NA     NA  
# ℹ 6,704 more rows
# ℹ 27 more variables: `1997` &lt;dbl&gt;, `1998` &lt;dbl&gt;, `1999` &lt;dbl&gt;, `2000` &lt;dbl&gt;,
#   `2001` &lt;dbl&gt;, `2002` &lt;dbl&gt;, `2003` &lt;dbl&gt;, `2004` &lt;dbl&gt;, `2005` &lt;dbl&gt;,
#   `2006` &lt;dbl&gt;, `2007` &lt;dbl&gt;, `2008` &lt;dbl&gt;, `2009` &lt;dbl&gt;, `2010` &lt;dbl&gt;,
#   `2011` &lt;dbl&gt;, `2012` &lt;dbl&gt;, `2013` &lt;dbl&gt;, `2014` &lt;dbl&gt;, `2015` &lt;dbl&gt;,
#   `2016` &lt;dbl&gt;, `2017` &lt;dbl&gt;, `2018` &lt;dbl&gt;, `2019` &lt;dbl&gt;, `2020` &lt;dbl&gt;,
#   `2021` &lt;dbl&gt;, `2022` &lt;dbl&gt;, `2023` &lt;dbl&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 161,136 × 16
   freq  sex   age    unit  isced11 geo   `1992` `1993` `1994` `1995` `1996`
   &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt; 
 1 A     F     Y15-64 PC    ED0-2   AT    :      :      :      41.4   39.6  
 2 A     F     Y15-64 PC    ED0-2   AT    :      :      :      41.4   39.6  
 3 A     F     Y15-64 PC    ED0-2   AT    :      :      :      41.4   39.6  
 4 A     F     Y15-64 PC    ED0-2   AT    :      :      :      41.4   39.6  
 5 A     F     Y15-64 PC    ED0-2   AT    :      :      :      41.4   39.6  
 6 A     F     Y15-64 PC    ED0-2   AT    :      :      :      41.4   39.6  
 7 A     F     Y15-64 PC    ED0-2   AT    :      :      :      41.4   39.6  
 8 A     F     Y15-64 PC    ED0-2   AT    :      :      :      41.4   39.6  
 9 A     F     Y15-64 PC    ED0-2   AT    :      :      :      41.4   39.6  
10 A     F     Y15-64 PC    ED0-2   AT    :      :      :      41.4   39.6  
# ℹ 161,126 more rows
# ℹ 5 more variables: `1997` &lt;chr&gt;, `1998` &lt;chr&gt;, `1999` &lt;chr&gt;, Years &lt;chr&gt;,
#   Value &lt;chr&gt;</code></pre>
</div>
</div>
</section>
</section>
<section id="patent-and-education-application" class="level1">
<h1>Patent and education application</h1>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="R-project-patent_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="R-project-patent_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(viridis)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Le chargement a nécessité le package : viridisLite</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>filtered_data <span class="ot">&lt;-</span> filtered_data <span class="sc">%&gt;%</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(geo) <span class="sc">%&gt;%</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">proportion =</span> patents <span class="sc">/</span> <span class="fu">sum</span>(patents) <span class="sc">*</span> <span class="dv">100</span>)  <span class="co"># add the proportion in percentage</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>plot_education_patents2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(filtered_data, </span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>         <span class="fu">aes</span>(<span class="at">x =</span> geo, </span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">y =</span> patents, </span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">fill =</span> educational_attainment)) <span class="sc">+</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"stack"</span>, <span class="at">width =</span> <span class="fl">0.7</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span>  <span class="co"># Adjust the borders of the sitcks</span></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste0</span>(<span class="fu">round</span>(proportion, <span class="dv">1</span>), <span class="st">"%"</span>)), </span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>              <span class="at">position =</span> <span class="fu">position_stack</span>(<span class="at">vjust =</span> <span class="fl">0.5</span>), <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span>  </span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_fill_viridis_d</span>(<span class="at">name =</span> <span class="st">"Education Level"</span>, <span class="at">option =</span> <span class="st">"C"</span>) <span class="sc">+</span>  </span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Country"</span>,</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> <span class="st">"Number of Patents"</span>,</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>         <span class="at">title =</span> <span class="st">"Patent Activity by Education Level and Country (2022)"</span>) <span class="sc">+</span></span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"right"</span>,</span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>          <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>          <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.1</span>))) </span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(plot_education_patents2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="R-project-patent_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="patent-and-key-indicator-application" class="level1">
<h1>Patent and key indicator application</h1>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Data Preparation - Filter for specific years</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>filtered_data2 <span class="ot">&lt;-</span> merged_data2 <span class="sc">%&gt;%</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>    geo <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"FR"</span>, <span class="st">"DE"</span>, <span class="st">"BG"</span>),  <span class="co"># Selected countries</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>    year <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">2012</span>, <span class="dv">2015</span>, <span class="dv">2018</span>, <span class="dv">2021</span>)  <span class="co"># Show only these years</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Create the plot</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>plot_key_patents <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>  filtered_data2, </span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> year, </span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> patents, </span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> sector,  <span class="co"># Different color for each sector</span></span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">linetype =</span> sector,  <span class="co"># Different line type for each sector</span></span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">group =</span> sector</span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Add lines</span></span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">size =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Add points to show exact values</span></span>
<span id="cb28-22"><a href="#cb28-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb28-23"><a href="#cb28-23" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Separate by country</span></span>
<span id="cb28-24"><a href="#cb28-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(</span>
<span id="cb28-25"><a href="#cb28-25" aria-hidden="true" tabindex="-1"></a>    <span class="sc">~</span> geo, </span>
<span id="cb28-26"><a href="#cb28-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">scales =</span> <span class="st">"free_y"</span>,</span>
<span id="cb28-27"><a href="#cb28-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">labeller =</span> <span class="fu">labeller</span>(<span class="at">geo =</span> <span class="fu">c</span>(</span>
<span id="cb28-28"><a href="#cb28-28" aria-hidden="true" tabindex="-1"></a>      <span class="st">"FR"</span> <span class="ot">=</span> <span class="st">"France"</span>,</span>
<span id="cb28-29"><a href="#cb28-29" aria-hidden="true" tabindex="-1"></a>      <span class="st">"DE"</span> <span class="ot">=</span> <span class="st">"Germany"</span>,</span>
<span id="cb28-30"><a href="#cb28-30" aria-hidden="true" tabindex="-1"></a>      <span class="st">"BG"</span> <span class="ot">=</span> <span class="st">"Bulgaria"</span></span>
<span id="cb28-31"><a href="#cb28-31" aria-hidden="true" tabindex="-1"></a>    ))</span>
<span id="cb28-32"><a href="#cb28-32" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb28-33"><a href="#cb28-33" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Adjust scales for better visibility</span></span>
<span id="cb28-34"><a href="#cb28-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>comma) <span class="sc">+</span>  <span class="co"># Add commas to numbers</span></span>
<span id="cb28-35"><a href="#cb28-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">2012</span>, <span class="dv">2015</span>, <span class="dv">2018</span>, <span class="dv">2021</span>)) <span class="sc">+</span>  <span class="co"># Show only selected years</span></span>
<span id="cb28-36"><a href="#cb28-36" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Customize colors</span></span>
<span id="cb28-37"><a href="#cb28-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_brewer</span>(<span class="at">palette =</span> <span class="st">"Set2"</span>) <span class="sc">+</span></span>
<span id="cb28-38"><a href="#cb28-38" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Labels</span></span>
<span id="cb28-39"><a href="#cb28-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb28-40"><a href="#cb28-40" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Year"</span>,</span>
<span id="cb28-41"><a href="#cb28-41" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of Patents"</span>,</span>
<span id="cb28-42"><a href="#cb28-42" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Patent Activity by Country"</span>,</span>
<span id="cb28-43"><a href="#cb28-43" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"Sector"</span>,</span>
<span id="cb28-44"><a href="#cb28-44" aria-hidden="true" tabindex="-1"></a>    <span class="at">linetype =</span> <span class="st">"Sector"</span></span>
<span id="cb28-45"><a href="#cb28-45" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb28-46"><a href="#cb28-46" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Theme customization</span></span>
<span id="cb28-47"><a href="#cb28-47" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb28-48"><a href="#cb28-48" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb28-49"><a href="#cb28-49" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"bottom"</span>,  <span class="co"># Move legend to bottom</span></span>
<span id="cb28-50"><a href="#cb28-50" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb28-51"><a href="#cb28-51" aria-hidden="true" tabindex="-1"></a>    <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>, <span class="at">face =</span> <span class="st">"bold"</span>),  <span class="co"># Country names</span></span>
<span id="cb28-52"><a href="#cb28-52" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">0</span>)  <span class="co"># Horizontal year labels</span></span>
<span id="cb28-53"><a href="#cb28-53" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb28-54"><a href="#cb28-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-55"><a href="#cb28-55" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Display the plot</span></span>
<span id="cb28-56"><a href="#cb28-56" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(plot_key_patents)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="R-project-patent_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="R-project-patent_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="description-of-the-data-joining-cleaning-etc.-for-combined-data" class="level2">
<h2 class="anchored" data-anchor-id="description-of-the-data-joining-cleaning-etc.-for-combined-data">Description of the data joining, cleaning, etc. for combined data</h2>
<p>We merged the 2 dataset we create earlier by their common variables: geo and country. And then we rename a column for clarity: country=geo</p>
</section>
<section id="regression" class="level2">
<h2 class="anchored" data-anchor-id="regression">Regression</h2>
<section id="panel-regression-panel-regression-with-lagged-effect" class="level3">
<h3 class="anchored" data-anchor-id="panel-regression-panel-regression-with-lagged-effect">Panel regression &amp; panel regression with lagged effect</h3>
<p>We wanted to do a panel data analysis but there’s a huge issue with duplicates we weren’t able to fixed. I put the code with #.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Checking for duplicate country-year combinations:"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 407 × 3
   country  year count
   &lt;chr&gt;   &lt;dbl&gt; &lt;int&gt;
 1 AL       2012     2
 2 AL       2013     2
 3 AL       2014     2
 4 AL       2015     2
 5 AL       2016     2
 6 AL       2017     2
 7 AL       2018     2
 8 AL       2019     2
 9 AL       2020     2
10 AL       2021     2
# ℹ 397 more rows</code></pre>
</div>
</div>
</section>
<section id="easier-regression" class="level3">
<h3 class="anchored" data-anchor-id="easier-regression">Easier regression</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="R-project-patent_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>In the graph above, the x-axis shows the fitted (predicted) values from the regression model, the y-axis shows the residuals (the differences between observed and predicted values) and the red dashed line represents zero on the residuals scale. We observe that most residuals are clustered around the zero line for lower fitted values (left side), which is good. However, there appears to be increasing spread and some extreme residuals as the fitted values increase (right side). Moreover, there’s evidence of heteroscedasticity (non-constant variance) since the spread of residuals isn’t consistent across fitted values. The spread appears to increase with larger fitted values. The pattern suggests that the model might be: - Performing better for smaller values, - Less reliable for larger values, - Potentially missing some important non-linear relationships</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing missing values or values outside the scale range
(`geom_line()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="R-project-patent_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Fixed Effects Regression Results:"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = patents.x ~ educational_attainment + sector + country + 
    year, data = model_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-7722.5  -301.6    21.1   266.7  6774.3 

Coefficients:
                                                               Estimate
(Intercept)                                                   4.412e+03
educational_attainmentTertiary to Doctoral                    8.670e-11
educational_attainmentUpper secondary (general)              -3.675e-11
educational_attainmentUpper secondary (vocational)            5.523e-11
educational_attainmentUpper secondary education and Doctoral  1.311e-11
sectorHouseholds                                              1.069e-09
sectorHouseholds and NPISHs                                  -6.997e-11
sectorNon-financial corporations                             -2.276e-10
sectorNon-financial/financial corporate sectors               5.701e-11
sectorTotal economy                                           7.266e-11
countryBE                                                    -2.116e+02
countryBG                                                    -4.896e+03
countryCH                                                     9.169e+03
countryCY                                                    -4.856e+03
countryCZ                                                    -4.471e+03
countryDE                                                     4.806e+04
countryDK                                                     6.426e+01
countryEE                                                    -4.809e+03
countryEL                                                    -4.699e+03
countryES                                                    -1.168e+03
countryEU27_2020                                              1.241e+05
countryFI                                                    -7.765e+02
countryFR                                                     1.610e+04
countryHR                                                    -4.923e+03
countryHU                                                    -4.624e+03
countryIE                                                    -3.383e+03
countryIS                                                    -4.649e+03
countryIT                                                     4.343e+03
countryLT                                                    -4.875e+03
countryLU                                                    -3.642e+03
countryLV                                                    -4.900e+03
countryMT                                                    -4.761e+03
countryNL                                                     8.387e+03
countryNO                                                    -3.586e+03
countryPL                                                    -3.837e+03
countryPT                                                    -4.548e+03
countryRO                                                    -4.822e+03
countryRS                                                    -4.949e+03
countrySE                                                     3.522e+03
countrySI                                                    -4.568e+03
countrySK                                                    -4.852e+03
countryTR                                                    -3.837e+03
year2013                                                      1.134e+02
year2014                                                      2.923e+02
year2015                                                      3.116e+02
year2016                                                      3.541e+02
year2017                                                      5.412e+02
year2018                                                      8.634e+02
year2019                                                      9.056e+02
year2020                                                      8.545e+02
year2021                                                      1.027e+03
year2022                                                      9.932e+02
                                                             Std. Error
(Intercept)                                                   4.023e+01
educational_attainmentTertiary to Doctoral                    1.584e+01
educational_attainmentUpper secondary (general)               1.584e+01
educational_attainmentUpper secondary (vocational)            1.584e+01
educational_attainmentUpper secondary education and Doctoral  1.584e+01
sectorHouseholds                                              2.523e+01
sectorHouseholds and NPISHs                                   2.421e+01
sectorNon-financial corporations                              2.518e+01
sectorNon-financial/financial corporate sectors               3.183e+01
sectorTotal economy                                           3.183e+01
countryBE                                                     3.922e+01
countryBG                                                     4.736e+01
countryCH                                                     3.922e+01
countryCY                                                     4.025e+01
countryCZ                                                     4.025e+01
countryDE                                                     4.025e+01
countryDK                                                     3.922e+01
countryEE                                                     3.922e+01
countryEL                                                     3.922e+01
countryES                                                     3.922e+01
countryEU27_2020                                              4.307e+01
countryFI                                                     3.922e+01
countryFR                                                     3.922e+01
countryHR                                                     4.025e+01
countryHU                                                     3.922e+01
countryIE                                                     3.922e+01
countryIS                                                     4.228e+01
countryIT                                                     3.922e+01
countryLT                                                     3.922e+01
countryLU                                                     3.922e+01
countryLV                                                     3.922e+01
countryMT                                                     3.922e+01
countryNL                                                     3.922e+01
countryNO                                                     4.025e+01
countryPL                                                     3.922e+01
countryPT                                                     3.922e+01
countryRO                                                     4.025e+01
countryRS                                                     4.489e+01
countrySE                                                     3.922e+01
countrySI                                                     3.922e+01
countrySK                                                     3.922e+01
countryTR                                                     4.496e+01
year2013                                                      2.349e+01
year2014                                                      2.349e+01
year2015                                                      2.349e+01
year2016                                                      2.349e+01
year2017                                                      2.349e+01
year2018                                                      2.349e+01
year2019                                                      2.349e+01
year2020                                                      2.349e+01
year2021                                                      2.349e+01
year2022                                                      2.349e+01
                                                              t value Pr(&gt;|t|)
(Intercept)                                                   109.660  &lt; 2e-16
educational_attainmentTertiary to Doctoral                      0.000    1.000
educational_attainmentUpper secondary (general)                 0.000    1.000
educational_attainmentUpper secondary (vocational)              0.000    1.000
educational_attainmentUpper secondary education and Doctoral    0.000    1.000
sectorHouseholds                                                0.000    1.000
sectorHouseholds and NPISHs                                     0.000    1.000
sectorNon-financial corporations                                0.000    1.000
sectorNon-financial/financial corporate sectors                 0.000    1.000
sectorTotal economy                                             0.000    1.000
countryBE                                                      -5.394 6.94e-08
countryBG                                                    -103.382  &lt; 2e-16
countryCH                                                     233.753  &lt; 2e-16
countryCY                                                    -120.634  &lt; 2e-16
countryCZ                                                    -111.079  &lt; 2e-16
countryDE                                                    1194.019  &lt; 2e-16
countryDK                                                       1.638    0.101
countryEE                                                    -122.617  &lt; 2e-16
countryEL                                                    -119.806  &lt; 2e-16
countryES                                                     -29.766  &lt; 2e-16
countryEU27_2020                                             2881.629  &lt; 2e-16
countryFI                                                     -19.798  &lt; 2e-16
countryFR                                                     410.371  &lt; 2e-16
countryHR                                                    -122.286  &lt; 2e-16
countryHU                                                    -117.883  &lt; 2e-16
countryIE                                                     -86.249  &lt; 2e-16
countryIS                                                    -109.981  &lt; 2e-16
countryIT                                                     110.719  &lt; 2e-16
countryLT                                                    -124.285  &lt; 2e-16
countryLU                                                     -92.849  &lt; 2e-16
countryLV                                                    -124.920  &lt; 2e-16
countryMT                                                    -121.392  &lt; 2e-16
countryNL                                                     213.834  &lt; 2e-16
countryNO                                                     -89.074  &lt; 2e-16
countryPL                                                     -97.824  &lt; 2e-16
countryPT                                                    -115.946  &lt; 2e-16
countryRO                                                    -119.777  &lt; 2e-16
countryRS                                                    -110.242  &lt; 2e-16
countrySE                                                      89.792  &lt; 2e-16
countrySI                                                    -116.469  &lt; 2e-16
countrySK                                                    -123.700  &lt; 2e-16
countryTR                                                     -85.352  &lt; 2e-16
year2013                                                        4.829 1.38e-06
year2014                                                       12.442  &lt; 2e-16
year2015                                                       13.266  &lt; 2e-16
year2016                                                       15.076  &lt; 2e-16
year2017                                                       23.037  &lt; 2e-16
year2018                                                       36.755  &lt; 2e-16
year2019                                                       38.549  &lt; 2e-16
year2020                                                       36.377  &lt; 2e-16
year2021                                                       43.730  &lt; 2e-16
year2022                                                       42.280  &lt; 2e-16
                                                                
(Intercept)                                                  ***
educational_attainmentTertiary to Doctoral                      
educational_attainmentUpper secondary (general)                 
educational_attainmentUpper secondary (vocational)              
educational_attainmentUpper secondary education and Doctoral    
sectorHouseholds                                                
sectorHouseholds and NPISHs                                     
sectorNon-financial corporations                                
sectorNon-financial/financial corporate sectors                 
sectorTotal economy                                             
countryBE                                                    ***
countryBG                                                    ***
countryCH                                                    ***
countryCY                                                    ***
countryCZ                                                    ***
countryDE                                                    ***
countryDK                                                       
countryEE                                                    ***
countryEL                                                    ***
countryES                                                    ***
countryEU27_2020                                             ***
countryFI                                                    ***
countryFR                                                    ***
countryHR                                                    ***
countryHU                                                    ***
countryIE                                                    ***
countryIS                                                    ***
countryIT                                                    ***
countryLT                                                    ***
countryLU                                                    ***
countryLV                                                    ***
countryMT                                                    ***
countryNL                                                    ***
countryNO                                                    ***
countryPL                                                    ***
countryPT                                                    ***
countryRO                                                    ***
countryRS                                                    ***
countrySE                                                    ***
countrySI                                                    ***
countrySK                                                    ***
countryTR                                                    ***
year2013                                                     ***
year2014                                                     ***
year2015                                                     ***
year2016                                                     ***
year2017                                                     ***
year2018                                                     ***
year2019                                                     ***
year2020                                                     ***
year2021                                                     ***
year2022                                                     ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 942.6 on 35368 degrees of freedom
  (187 observations effacées parce que manquantes)
Multiple R-squared:  0.998, Adjusted R-squared:  0.998 
F-statistic: 3.489e+05 on 51 and 35368 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "\nRobust Standard Errors (Clustered by Country):"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
t test of coefficients:

                                                                Estimate
(Intercept)                                                   4.4118e+03
educational_attainmentTertiary to Doctoral                    8.6695e-11
educational_attainmentUpper secondary (general)              -3.6752e-11
educational_attainmentUpper secondary (vocational)            5.5234e-11
educational_attainmentUpper secondary education and Doctoral  1.3108e-11
sectorHouseholds                                              1.0685e-09
sectorHouseholds and NPISHs                                  -6.9970e-11
sectorNon-financial corporations                             -2.2758e-10
sectorNon-financial/financial corporate sectors               5.7011e-11
sectorTotal economy                                           7.2656e-11
countryBE                                                    -2.1157e+02
countryBG                                                    -4.8965e+03
countryCH                                                     9.1686e+03
countryCY                                                    -4.8560e+03
countryCZ                                                    -4.4714e+03
countryDE                                                     4.8064e+04
countryDK                                                     6.4256e+01
countryEE                                                    -4.8095e+03
countryEL                                                    -4.6992e+03
countryES                                                    -1.1675e+03
countryEU27_2020                                              1.2410e+05
countryFI                                                    -7.7653e+02
countryFR                                                     1.6096e+04
countryHR                                                    -4.9225e+03
countryHU                                                    -4.6238e+03
countryIE                                                    -3.3830e+03
countryIS                                                    -4.6495e+03
countryIT                                                     4.3428e+03
countryLT                                                    -4.8749e+03
countryLU                                                    -3.6419e+03
countryLV                                                    -4.8998e+03
countryMT                                                    -4.7614e+03
countryNL                                                     8.3873e+03
countryNO                                                    -3.5856e+03
countryPL                                                    -3.8370e+03
countryPT                                                    -4.5478e+03
countryRO                                                    -4.8215e+03
countryRS                                                    -4.9488e+03
countrySE                                                     3.5219e+03
countrySI                                                    -4.5683e+03
countrySK                                                    -4.8520e+03
countryTR                                                    -3.8372e+03
year2013                                                      1.1343e+02
year2014                                                      2.9229e+02
year2015                                                      3.1163e+02
year2016                                                      3.5415e+02
year2017                                                      5.4118e+02
year2018                                                      8.6342e+02
year2019                                                      9.0557e+02
year2020                                                      8.5455e+02
year2021                                                      1.0273e+03
year2022                                                      9.9321e+02
                                                              Std. Error
(Intercept)                                                   2.4286e+02
educational_attainmentTertiary to Doctoral                    4.8153e-11
educational_attainmentUpper secondary (general)               5.5384e-11
educational_attainmentUpper secondary (vocational)            5.5321e-11
educational_attainmentUpper secondary education and Doctoral  5.5272e-11
sectorHouseholds                                              2.2671e-11
sectorHouseholds and NPISHs                                   4.3048e-11
sectorNon-financial corporations                              3.5655e-11
sectorNon-financial/financial corporate sectors               8.4966e-11
sectorTotal economy                                           8.0357e-11
countryBE                                                     2.9265e-12
countryBG                                                     5.9058e-12
countryCH                                                     1.4180e-12
countryCY                                                     1.9123e-12
countryCZ                                                     2.4416e-12
countryDE                                                     1.9463e-12
countryDK                                                     4.7634e-12
countryEE                                                     1.9224e-12
countryEL                                                     1.5878e-12
countryES                                                     3.2674e-12
countryEU27_2020                                              6.4165e-12
countryFI                                                     1.4409e-12
countryFR                                                     5.2266e-12
countryHR                                                     2.6830e-12
countryHU                                                     2.0322e-12
countryIE                                                     1.6455e-12
countryIS                                                     6.8275e-12
countryIT                                                     1.3784e-12
countryLT                                                     2.3928e-12
countryLU                                                     1.4057e-12
countryLV                                                     1.6598e-12
countryMT                                                     1.9905e-12
countryNL                                                     1.4424e-12
countryNO                                                     1.6231e-12
countryPL                                                     2.5586e-12
countryPT                                                     1.6476e-12
countryRO                                                     1.6593e-12
countryRS                                                     6.5860e-12
countrySE                                                     2.2349e-12
countrySI                                                     1.4951e-12
countrySK                                                     2.1393e-12
countryTR                                                     9.6573e-12
year2013                                                      9.5858e+01
year2014                                                      1.9904e+02
year2015                                                      2.3693e+02
year2016                                                      2.2947e+02
year2017                                                      2.6233e+02
year2018                                                      3.4112e+02
year2019                                                      3.5029e+02
year2020                                                      3.2231e+02
year2021                                                      3.9939e+02
year2022                                                      4.1998e+02
                                                                 t value
(Intercept)                                                   1.8166e+01
educational_attainmentTertiary to Doctoral                    1.8004e+00
educational_attainmentUpper secondary (general)              -6.6360e-01
educational_attainmentUpper secondary (vocational)            9.9840e-01
educational_attainmentUpper secondary education and Doctoral  2.3720e-01
sectorHouseholds                                              4.7133e+01
sectorHouseholds and NPISHs                                  -1.6254e+00
sectorNon-financial corporations                             -6.3827e+00
sectorNon-financial/financial corporate sectors               6.7100e-01
sectorTotal economy                                           9.0420e-01
countryBE                                                    -7.2294e+13
countryBG                                                    -8.2911e+14
countryCH                                                     6.4660e+15
countryCY                                                    -2.5394e+15
countryCZ                                                    -1.8313e+15
countryDE                                                     2.4695e+16
countryDK                                                     1.3490e+13
countryEE                                                    -2.5018e+15
countryEL                                                    -2.9596e+15
countryES                                                    -3.5732e+14
countryEU27_2020                                              1.9341e+16
countryFI                                                    -5.3892e+14
countryFR                                                     3.0797e+15
countryHR                                                    -1.8347e+15
countryHU                                                    -2.2753e+15
countryIE                                                    -2.0559e+15
countryIS                                                    -6.8100e+14
countryIT                                                     3.1505e+15
countryLT                                                    -2.0374e+15
countryLU                                                    -2.5909e+15
countryLV                                                    -2.9520e+15
countryMT                                                    -2.3920e+15
countryNL                                                     5.8147e+15
countryNO                                                    -2.2091e+15
countryPL                                                    -1.4996e+15
countryPT                                                    -2.7603e+15
countryRO                                                    -2.9057e+15
countryRS                                                    -7.5140e+14
countrySE                                                     1.5759e+15
countrySI                                                    -3.0555e+15
countrySK                                                    -2.2680e+15
countryTR                                                    -3.9734e+14
year2013                                                      1.1834e+00
year2014                                                      1.4685e+00
year2015                                                      1.3153e+00
year2016                                                      1.5433e+00
year2017                                                      2.0630e+00
year2018                                                      2.5312e+00
year2019                                                      2.5852e+00
year2020                                                      2.6513e+00
year2021                                                      2.5721e+00
year2022                                                      2.3649e+00
                                                              Pr(&gt;|t|)    
(Intercept)                                                  &lt; 2.2e-16 ***
educational_attainmentTertiary to Doctoral                    0.071806 .  
educational_attainmentUpper secondary (general)               0.506961    
educational_attainmentUpper secondary (vocational)            0.318079    
educational_attainmentUpper secondary education and Doctoral  0.812533    
sectorHouseholds                                             &lt; 2.2e-16 ***
sectorHouseholds and NPISHs                                   0.104084    
sectorNon-financial corporations                             1.761e-10 ***
sectorNon-financial/financial corporate sectors               0.502237    
sectorTotal economy                                           0.365914    
countryBE                                                    &lt; 2.2e-16 ***
countryBG                                                    &lt; 2.2e-16 ***
countryCH                                                    &lt; 2.2e-16 ***
countryCY                                                    &lt; 2.2e-16 ***
countryCZ                                                    &lt; 2.2e-16 ***
countryDE                                                    &lt; 2.2e-16 ***
countryDK                                                    &lt; 2.2e-16 ***
countryEE                                                    &lt; 2.2e-16 ***
countryEL                                                    &lt; 2.2e-16 ***
countryES                                                    &lt; 2.2e-16 ***
countryEU27_2020                                             &lt; 2.2e-16 ***
countryFI                                                    &lt; 2.2e-16 ***
countryFR                                                    &lt; 2.2e-16 ***
countryHR                                                    &lt; 2.2e-16 ***
countryHU                                                    &lt; 2.2e-16 ***
countryIE                                                    &lt; 2.2e-16 ***
countryIS                                                    &lt; 2.2e-16 ***
countryIT                                                    &lt; 2.2e-16 ***
countryLT                                                    &lt; 2.2e-16 ***
countryLU                                                    &lt; 2.2e-16 ***
countryLV                                                    &lt; 2.2e-16 ***
countryMT                                                    &lt; 2.2e-16 ***
countryNL                                                    &lt; 2.2e-16 ***
countryNO                                                    &lt; 2.2e-16 ***
countryPL                                                    &lt; 2.2e-16 ***
countryPT                                                    &lt; 2.2e-16 ***
countryRO                                                    &lt; 2.2e-16 ***
countryRS                                                    &lt; 2.2e-16 ***
countrySE                                                    &lt; 2.2e-16 ***
countrySI                                                    &lt; 2.2e-16 ***
countrySK                                                    &lt; 2.2e-16 ***
countryTR                                                    &lt; 2.2e-16 ***
year2013                                                      0.236676    
year2014                                                      0.141981    
year2015                                                      0.188411    
year2016                                                      0.122755    
year2017                                                      0.039119 *  
year2018                                                      0.011373 *  
year2019                                                      0.009737 ** 
year2020                                                      0.008022 ** 
year2021                                                      0.010113 *  
year2022                                                      0.018040 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Surprisingly, we observe that educational attainment levels show minimal and statistically insignificant effects on patent applications. For example: Tertiary to Doctoral Education Coefficient: 8.670e-11 (extremely small positive effect) Marginal significance (p = 0.071) This suggests that for each percentage point increase in the population with tertiary to doctoral education, there is virtually no measurable impact on patent applications This unexpected result suggests that the relationship between education and patents might be more complex than directly measurable, possibly operating through other channels or requiring different measurement approaches. Indeed there 3 possible things that can explain this result: 1) Scale Issue: The variables might need rescaling (e.g., education in percentages while patents in absolute numbers) 2) Model Specification: The relationship might be non-linear or requiring interaction terms 3) Data Structure: The strong country fixed effects might be absorbing most of the education-related variance</p>
<p>In fact, There are substantial and highly significant differences between countries in patent applications: Leading innovators: Germany (+48,064), France (+16,096), Switzerland (+9,169), Netherlands (+8,387) Lower patent activity: Many Eastern European countries show significantly negative coefficients, indicating structural differences in innovation systems These large country effects suggest that national innovation systems, institutional quality, and industrial base may be more important than educational metrics alone.</p>
<p>Furthermore, we observe clear upward trend in patent applications over time: Significant positive year effects from 2017-2022 Strongest effects in recent years (2021: +1,027, 2022: +993) This suggests improving innovation capacity across Europe over time</p>
<p>Finally, there’s a sector effect, we observe significant differences across sectors: Non-financial corporations show significant negative effects while Household sector shows significant positive effects This indicates the importance of considering institutional structures in innovation.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "\nModel Fit Statistics:"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "R-squared: 0.998"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Adjusted R-squared: 0.998"</code></pre>
</div>
</div>
<p>We have a R-squared: 0.998 which mean that 99.8% of the variance in patent applications is explained by the independent variables in the model (educational attainment, sector, and year). The model is a very good fit for the data. Almost all the variation in the outcome variable (patent applications) is being explained by the predictors we have included. Moreover, since R-squared and Adjusted R-squared are the same, this suggests that you are not overfitting the model. It means that the model’s explanatory power is due to the actual relationship between the independent variables and the dependent variable, rather than just adding more predictors for the sake of increasing the R-squared.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                           GVIF Df GVIF^(1/(2*Df))
educational_attainment 1.000000  4        1.000000
sector                 1.033977  5        1.003347
country                1.033977 32        1.000522
year                   1.000000 10        1.000000</code></pre>
</div>
</div>
<p>The GVIF and GVIF^(1/(2*Df)) values are all very close to 1, with only minor exceptions for sector and country, which have GVIF values slightly above 1. These small values suggest that multicollinearity is not a major concern in your model.The absence of large GVIF values (i.e., values much greater than 1) indicates that multicollinearity is not severe, and the regression coefficients should be reliable.The slight inflation observed for sector and country indicates minor correlations with other variables, but these are not likely to cause significant issues with model estimation.</p>
</section>
<section id="differences-between-region-cee-and-we" class="level3">
<h3 class="anchored" data-anchor-id="differences-between-region-cee-and-we">Differences between region (CEE and WE)</h3>
<p>We will create two groups of countries to compare their innovation dynamics based on a study by Stojkoski et al.&nbsp;(2021), titled “Differences in innovation relationships between Central and Eastern Europe and Western Europe: Evidence from CIS 2014”.</p>
<p>To replicate this approach and explore further the differences between countries we observe in the regression, we will group the countries as follows:</p>
<p>Central and Eastern Europe (CEE): This group includes countries such as Bulgaria (BG), Croatia (HR), Hungary(HU), Romania(RO), and Slovakia(SK). Western Europe (WE): This group consists of Greece(EL), Spain(ES), Norway(NO), and Portugal(PT).</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="R-project-patent_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We observe notable differences in patent applications between the two groups on the map. Specifically, Western European countries tend to have higher patent application rates compared to their counterparts in Central and Eastern Europe. To better understand these disparities, we will conduct a regression analysis to further explore the differences.</p>
<section id="regression-1" class="level4">
<h4 class="anchored" data-anchor-id="regression-1">Regression</h4>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 22 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 22 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="R-project-patent_files/figure-html/unnamed-chunk-50-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print results</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Western Countries Regression Results:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Western Countries Regression Results:"</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(western_robust)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
t test of coefficients:

                                                                Estimate
(Intercept)                                                   1.3008e+03
educational_attainmentTertiary to Doctoral                    3.7220e-12
educational_attainmentUpper secondary (general)               3.9383e-12
educational_attainmentUpper secondary (vocational)            3.1512e-12
educational_attainmentUpper secondary education and Doctoral  3.8273e-12
sectorHouseholds                                              5.3523e-12
sectorHouseholds and NPISHs                                   5.9985e-12
sectorNon-financial corporations                              9.5072e+00
sectorNon-financial/financial corporate sectors               5.2591e-12
sectorTotal economy                                           8.3651e-12
year2013                                                     -3.0126e+01
year2014                                                     -7.0587e+00
year2015                                                      2.2204e+00
year2016                                                      4.4304e+01
year2017                                                      1.4690e+02
year2018                                                      2.9498e+02
year2019                                                      3.8960e+02
year2020                                                      3.2761e+02
year2021                                                      3.4972e+02
year2022                                                      4.5935e+02
                                                              Std. Error
(Intercept)                                                   1.2252e+02
educational_attainmentTertiary to Doctoral                    6.7771e+01
educational_attainmentUpper secondary (general)               6.7771e+01
educational_attainmentUpper secondary (vocational)            6.7771e+01
educational_attainmentUpper secondary education and Doctoral  6.7771e+01
sectorHouseholds                                              1.0503e+02
sectorHouseholds and NPISHs                                   1.0170e+02
sectorNon-financial corporations                              1.0706e+02
sectorNon-financial/financial corporate sectors               1.3560e+02
sectorTotal economy                                           1.3560e+02
year2013                                                      9.3000e+01
year2014                                                      9.1466e+01
year2015                                                      9.2168e+01
year2016                                                      9.4228e+01
year2017                                                      9.9230e+01
year2018                                                      1.0098e+02
year2019                                                      1.0280e+02
year2020                                                      1.0013e+02
year2021                                                      9.8974e+01
year2022                                                      1.0340e+02
                                                             t value  Pr(&gt;|t|)
(Intercept)                                                  10.6165 &lt; 2.2e-16
educational_attainmentTertiary to Doctoral                    0.0000 1.0000000
educational_attainmentUpper secondary (general)               0.0000 1.0000000
educational_attainmentUpper secondary (vocational)            0.0000 1.0000000
educational_attainmentUpper secondary education and Doctoral  0.0000 1.0000000
sectorHouseholds                                              0.0000 1.0000000
sectorHouseholds and NPISHs                                   0.0000 1.0000000
sectorNon-financial corporations                              0.0888 0.9292400
sectorNon-financial/financial corporate sectors               0.0000 1.0000000
sectorTotal economy                                           0.0000 1.0000000
year2013                                                     -0.3239 0.7460029
year2014                                                     -0.0772 0.9384895
year2015                                                      0.0241 0.9807815
year2016                                                      0.4702 0.6382543
year2017                                                      1.4804 0.1388412
year2018                                                      2.9211 0.0035049
year2019                                                      3.7898 0.0001528
year2020                                                      3.2718 0.0010766
year2021                                                      3.5334 0.0004143
year2022                                                      4.4424 9.108e-06
                                                                
(Intercept)                                                  ***
educational_attainmentTertiary to Doctoral                      
educational_attainmentUpper secondary (general)                 
educational_attainmentUpper secondary (vocational)              
educational_attainmentUpper secondary education and Doctoral    
sectorHouseholds                                                
sectorHouseholds and NPISHs                                     
sectorNon-financial corporations                                
sectorNon-financial/financial corporate sectors                 
sectorTotal economy                                             
year2013                                                        
year2014                                                        
year2015                                                        
year2016                                                        
year2017                                                        
year2018                                                     ** 
year2019                                                     ***
year2020                                                     ** 
year2021                                                     ***
year2022                                                     ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Eastern Countries Regression Results:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "\nEastern Countries Regression Results:"</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(eastern_robust)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
t test of coefficients:

                                                                Estimate
(Intercept)                                                   1.2759e+02
educational_attainmentTertiary to Doctoral                   -2.9516e-13
educational_attainmentUpper secondary (general)              -4.6120e-13
educational_attainmentUpper secondary (vocational)           -5.3035e-13
educational_attainmentUpper secondary education and Doctoral -1.5603e-13
sectorHouseholds                                              1.3951e+01
sectorHouseholds and NPISHs                                   8.1378e+00
sectorNon-financial corporations                              1.7976e+01
sectorNon-financial/financial corporate sectors               1.6994e-13
sectorTotal economy                                           3.3461e-13
year2013                                                      6.4901e+00
year2014                                                      1.3887e+01
year2015                                                      2.0161e+01
year2016                                                      2.2054e+01
year2017                                                      3.3053e+01
year2018                                                      7.1020e+01
year2019                                                      4.6134e+01
year2020                                                      5.9764e+01
year2021                                                      1.0074e+01
year2022                                                      4.4280e+01
                                                              Std. Error
(Intercept)                                                   8.7288e+00
educational_attainmentTertiary to Doctoral                    5.0323e+00
educational_attainmentUpper secondary (general)               5.0323e+00
educational_attainmentUpper secondary (vocational)            5.0323e+00
educational_attainmentUpper secondary education and Doctoral  5.0323e+00
sectorHouseholds                                              7.3731e+00
sectorHouseholds and NPISHs                                   7.0390e+00
sectorNon-financial corporations                              7.4892e+00
sectorNon-financial/financial corporate sectors               9.2989e+00
sectorTotal economy                                           9.2989e+00
year2013                                                      7.7015e+00
year2014                                                      7.9321e+00
year2015                                                      6.9322e+00
year2016                                                      7.0580e+00
year2017                                                      7.2224e+00
year2018                                                      7.9247e+00
year2019                                                      7.0534e+00
year2020                                                      7.2898e+00
year2021                                                      7.1849e+00
year2022                                                      6.6777e+00
                                                             t value  Pr(&gt;|t|)
(Intercept)                                                  14.6174 &lt; 2.2e-16
educational_attainmentTertiary to Doctoral                    0.0000  1.000000
educational_attainmentUpper secondary (general)               0.0000  1.000000
educational_attainmentUpper secondary (vocational)            0.0000  1.000000
educational_attainmentUpper secondary education and Doctoral  0.0000  1.000000
sectorHouseholds                                              1.8921  0.058538
sectorHouseholds and NPISHs                                   1.1561  0.247694
sectorNon-financial corporations                              2.4002  0.016421
sectorNon-financial/financial corporate sectors               0.0000  1.000000
sectorTotal economy                                           0.0000  1.000000
year2013                                                      0.8427  0.399434
year2014                                                      1.7507  0.080051
year2015                                                      2.9084  0.003649
year2016                                                      3.1247  0.001790
year2017                                                      4.5764 4.845e-06
year2018                                                      8.9619 &lt; 2.2e-16
year2019                                                      6.5406 6.740e-11
year2020                                                      8.1983 3.071e-16
year2021                                                      1.4021  0.160949
year2022                                                      6.6311 3.686e-11
                                                                
(Intercept)                                                  ***
educational_attainmentTertiary to Doctoral                      
educational_attainmentUpper secondary (general)                 
educational_attainmentUpper secondary (vocational)              
educational_attainmentUpper secondary education and Doctoral    
sectorHouseholds                                             .  
sectorHouseholds and NPISHs                                     
sectorNon-financial corporations                             *  
sectorNon-financial/financial corporate sectors                 
sectorTotal economy                                             
year2013                                                        
year2014                                                     .  
year2015                                                     ** 
year2016                                                     ** 
year2017                                                     ***
year2018                                                     ***
year2019                                                     ***
year2020                                                     ***
year2021                                                        
year2022                                                     ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Summary Statistics:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "\nSummary Statistics:"</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(summary_stats)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 6
  country_group mean_patents sd_patents n_obs r_squared_western
  &lt;chr&gt;                &lt;dbl&gt;      &lt;dbl&gt; &lt;int&gt;             &lt;dbl&gt;
1 CEE                   168.       115.  5005            0.0151
2 Other               10289.     24155. 26092            0.0151
3 WE                   1483.      1447.  4510            0.0151
# ℹ 1 more variable: r_squared_eastern &lt;dbl&gt;</code></pre>
</div>
</div>
<p>We observe that, mean, sd, the R-squared of western is lower than the one of the eastern so the eastern countries patent application variation are more expalined by the variable sector and educational attainment (our model). However, there’s 495 more observation in the central and eastern group than in the western group, this have effect on the R-squared, indeed, The group with more observations will likely have a more stable and robust R-squared value, while the smaller group might produce a less reliable one. So we need additional computation to conclude. We use a adjusted R-squarded becuase it’s less sensitive to sample size differences and gives a more accurate measure of how well the model fits the data when comparing groups with unequal sample sizes.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get Adjusted R-squared for Western group</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>adjusted_r_squared_western <span class="ot">&lt;-</span> <span class="fu">summary</span>(western_reg)<span class="sc">$</span>adj.r.squared</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Get Adjusted R-squared for Eastern group</span></span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>adjusted_r_squared_eastern <span class="ot">&lt;-</span> <span class="fu">summary</span>(eastern_reg)<span class="sc">$</span>adj.r.squared</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Print Adjusted R-squared values</span></span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Adjusted R-squared for Western group:"</span>, <span class="fu">round</span>(adjusted_r_squared_western, <span class="dv">4</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Adjusted R-squared for Western group: 0.011"</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Adjusted R-squared for Eastern group:"</span>, <span class="fu">round</span>(adjusted_r_squared_eastern, <span class="dv">4</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Adjusted R-squared for Eastern group: 0.0357"</code></pre>
</div>
</div>
<p>Both groups have low Adjusted R-squared values, which suggests that the independent variables included in the model (educational attainment, sector, and year) do not explain much of the variance in patent applications. 1.1% of the variance in patent applications in Western countries is explained by the variables in your model (educational attainment, sector, and year). For central and eastern countries it slighlty higher approximately 3.57% of the variance in patent applications in Eastern countries is explained by the same model. This may be due to the fact that patent applications are influenced by many other factors, such as policy environments, cultural factors, economic conditions, or innovation ecosystems, which are not captured by this model.</p>
<p>Comparison between groups: While the Eastern group has a slightly higher Adjusted R-squared than the Western group, both values are quite low, so the difference is not substantial. It suggests that the independent variables explain similarly small portions of the variance in both groups, and the model might not be a strong predictor for either group.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning in pf(f_stat, k, n1 + n2 - 2 * k): Production de NaN</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "\nChow Test Results:"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "F-statistic: -3365.6759"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "p-value: NaN"</code></pre>
</div>
</div>
</section>
</section>
</section>
</section>
<section id="iv--conclusion" class="level1">
<h1>IV- conclusion</h1>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>